# docker-compose up -d
# docker-compose exec gcloud bash
# OR docker-compose run --rm gcloud bash --login for use without kubeproxy
version: '2'
services:
  proxy: # kubectl proxy/port-foward bind to localhost only
    image: nginx
    volumes: 
      - ./nginx-config:/etc/nginx/conf.d:ro
    ports:
      - "8001:8002" # kubectl proxy default port
      - "8080:8081" # kubectl port-forward POD 8080:REMOTE_PORT
      - "8181:8182" # kubectl port-forward POD 8181:REMOTE_PORT
      - "8101:8101"
  gcloud:
    build: docker-gcloud
    environment:
      #DOCKER_TLS_VERIFY: "1"
      #DOCKER_HOST: "tcp://192.168.99.100:2376"
      #DOCKER_CERT_PATH: "/docker-certs"
      #DOCKER_MACHINE_NAME: "conrad"
      VAULT_ADDR: "https://vault.mgmt.conrad24.com:8200"
      VAULT_TOKEN: TODO
    volumes:
      - ./gcloud-config:/root/.config/gcloud
      - ./kube-config:/root/.kube
      - ./bash-history/.bash_history:/root/.bash_history
      - /Users/philippmeier/.docker/machine/machines/conrad:/docker-certs
      - ./terraform:/terraform
      - /Users/philippmeier/conrad:/conrad
      - /Users/philippmeier/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    command: kubectl proxy
    network_mode: service:proxy
